modLoader="javafml"
loaderVersion="[43,)"
license="Modified-MIT-License"

[[mods]]
modId="colorfulazaleas"
version="${file.jarVersion}"
displayName="ColorfulAzaleas"
logoFile="colorfulazaleas.png"
# credits="Thanks for this example mod goes to Java"
authors="Kekie6"
description='''
Adds more colorful Azalea trees to your world!
'''

[[dependencies.colorfulazaleas]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.colorfulazaleas]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
